### PR TITLE
ci: empty commit to trigger CI

### PR DESCRIPTION
**Pull request by joanise**

### CODE REVIEW

**Comment by dhdaines** [comment]
Hmm, looks like there's a missing build dependency on ninja in there somewhere...

**Comment by cclauss** [comment]
> ERROR: setuptools==59.6.0 is used in combination with setuptools_scm>=8.x

**Comment by joanise** [comment]
I'm not sure where to force the setuptools version, declaring it in the build-system requires didn't work...

**Comment by joanise** [comment]
Alright, I have to admit I'm at a loss here. Where is this setuptools 59 coming from?

**Comment by cclauss** [comment]
YAML's Norway problem!!! https://dev.to/hugovk/the-python-3-1-problem-85g

**Comment by joanise** [comment]
Yeah, I got bit by 3.10==3.1. LOL

But I got it now. On MacOS and Windows, `action/setup-python` work fine even if you don't explicitly declare a Python version, but on Linux it does not. And I think the difference is from an earlier comment you made: we need a venv, and `action/setup-python` only actually creates it if you declare the version explicitly. Otherwise you get 
> Warning: The `python-version` input is not set.  The version of Python currently in `PATH` will be used.

which basically means that using that action without a version is a no-op.

**Pull request merged**
