### PR TITLE
pre-commit autoupdate 2024-12-11

### PR DESCRIPTION
**Pull request by cclauss**
### PR Goal? 

% `pre-commit autoupdate && pre-commit run --all-files`
```
[https://github.com/pre-commit/pre-commit-hooks] updating v3.2.0 -> v5.0.0
[https://github.com/psf/black] updating 24.3.0 -> 24.10.0 -- REVERTED
[https://github.com/pre-commit/mirrors-mypy] updating v0.991 -> v1.13.0 -- REVERTED
[https://github.com/PyCQA/isort] updating 5.11.4 -> 5.13.2
[https://github.com/pre-commit/mirrors-clang-format] updating v15.0.7 -> v19.1.5
```
The file changes seem to all be about the `clang-format`upgrade.

### CODE REVIEW

**Comment by joanise** [comment]
I agree with the python-related changes to pre-commit, I'll let @dhdaines review the clang bits since I don't touch that code.

**Comment by cclauss** [comment]
@joanise you might try on a local branch:
`pre-commit autoupdate && pre-commit run --all-files`
and see if you can fix the `black` and `mypy` issues?

**Comment by joanise** [comment]
Black: since we still want to support Python 3.8, we could bump to 24.8 but not 24.10.
mypy: possibly, when I have some more time to put on this.

Question: is this causing any issue in a project you're working on? I'd like to know where I should put this in my priority list.

**Comment by cclauss** [comment]
black -- Perhaps upgrade to `ruff format` instead.

**Comment by dhdaines** [comment]
Ruff is nice and fast though it isn't always 100% compatible with `black`.

The C-related changes seem good to me, I think clang-format changed a bit the treatment of preprocessor macros but the result is much more readable.

**Review by dhdaines — APPROVED** [review]

**Pull request merged**
