### PR TITLE
Fix typos discovered by codespell

### PR DESCRIPTION
**Pull request by cclauss**
### PR Goal? 

Fix typos with https://pypi.org/project/codespell

% `codespell --ignore-words-list=avance,delt --skip="dict.txt,*.pyx" --write-changes`

### CODE REVIEW

**Comment by joanise** [comment]
Thanks for submitting this PR! Yes, fixing the typos is a good idea.

**Comment by cclauss** [comment]
Looking at failing test....

**Comment by joanise** [comment]
> Fixed at failing test? Modern OSes mandate a "managed" system Python where pip cannot install without a venv.

Ah, I was wondering why this workflow did use the actions/setup-python, I guess it's a leftover from old CI files, because we use it everywhere else in our projects.

I thought it might have been related to our old use of `requirements.dev.txt` instead of a `.[dev]` install defined in `pyproject.toml`, but maybe not.

Hum, no, it's more complex: it's still failing, both your patch and my attempt in #69

**Comment by joanise** [comment]
BTW, if you want to exercise the CI in your fork without having to wait for my approval, you can create a PR from your branch to your own main and then you'll be able to troubleshoot on your side.

**Comment by joanise** [comment]
And thanks for your help here, but don't feel obligated, we'll figure it out.

**Comment by cclauss** [comment]
requires = [ "setuptools>=61.2" ]

**Comment by cclauss** [comment]
I reverted all non-codespell changes.

**Comment by joanise** [comment]
Urgh, CI ran on the old merge commit, not on the new one with my PR merged. Grrr.

**Comment by joanise** [comment]
Approving anyway, we know this is fixed.

**Review by joanise — APPROVED** [review]

**Comment by dhdaines** [comment]
Oh, thanks!  I was wondering about that CI failure...

**Pull request merged**
